# Generated by Django 3.0.7 on 2020-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='nb_acces',
            field=models.IntegerField(default=0, verbose_name="Nombres d'accès à l'URL"),
        ),
    ]
