# Generated by Django 3.0.7 on 2020-07-15 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_auto_20200715_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
    ]
