# Generated by Django 3.0.7 on 2020-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0003_auto_20200715_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
    ]
